management:
  endpoints:
    web:
      exposure:
        include: health,shutdown,prometheus
      base-path: /
      path-mapping:
        health: health
        shutdown: shutdown
        prometheus: metrics
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    rabbit:
      enabled: false
  server:
    port: ${MANAGEMENT_PORT:9000}

server:
  port: ${SERVER_PORT:8000}
